# Generated by Django 4.2.10 on 2024-02-24 16:24

from django.db import migrations, models
import unetApp.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Images",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unMaskedImage",
                    models.ImageField(
                        blank=True, null=True, upload_to=unetApp.models.upload_path
                    ),
                ),
            ],
        ),
    ]
