# Generated by Django 5.0.2 on 2024-02-25 04:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("unetApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="images",
            name="predictedMask",
            field=models.ImageField(blank=True, null=True, upload_to="images/masked/"),
        ),
    ]
